Algoritmo "minutos e horas"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2023

Var
horas, min, conversao: real


Inicio
// entrada
escreval ("digite quantas horas: ")
leia (horas)

escreval ("digite quantos minutos: ")
leia (min)

//processamento
conversao <- (min/60)+ horas

//saida
escreval ("    RESULTADO    ")
escreval ("o resultado é: ", conversao)


Fimalgoritmo