Algoritmo "area quadrado"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2023

Var
 area, perimetro,lado : real

//entrada
Inicio
escreval("digite a lado do quadrado: ")
leia (lado)

//processamento
area <- lado * lado
perimetro <- lado * 4

//saida
escreval("a area do quadrado : ", area)
escreval ("o perimetro do quadrado : ", perimetro)

Fimalgoritmo